#!/usr/bin/env bash
#
# Start Home Assistant Test Container
#
# Usage:
#   .ralph/scripts/start_test_ha.sh           # Start container and wait
#   .ralph/scripts/start_test_ha.sh --wait    # Wait only if container exists
#
# This script:
# - Starts the HA test container using pre-configured volume
# - Pre-configured state: onboarding bypass, admin user, HACS, mock sensors
# - IMPORTANT: Does NOT clean up the container (persists for debugging)
# - IMPORTANT: Does NOT restart container if already running (to avoid volume issues)
#
# The volume (test-ha/config/) already contains:
#   - .storage/onboarding - bypass onboarding
#   - .storage/auth - admin user configured
#   - custom_components/hacs/ - HACS pre-installed
#   - input_*.yaml, template_sensors.yaml - mock sensors
#
set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEST_HA_DIR="$PROJECT_DIR/test-ha"
HA_CONTAINER="ha-ev-test"
HA_URL="${HA_URL:-http://localhost:8123}"
WAIT_SECONDS="${WAIT_SECONDS:-180}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info()  { echo -e "${BLUE}[INFO]${NC} $1"; }
log_ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================================================
# INTEGRATION SOURCE RESOLUTION
# Priority order:
# 1. WORKTREE_PATH (set by ralph-loop) - explicit worktree
# 2. Last used worktree (saved in .worktrees/last_worktree) - automatic fallback
# 3. PROJECT_DIR (main repo) - manual execution fallback (WARNING)
# ============================================================================

INTEGRATION_SOURCE=""
WORKTREE_PATH=""

# First, check if WORKTREE_PATH is explicitly set by ralph-loop
if [[ -n "${WORKTREE_PATH:-}" ]]; then
    WORKTREE_PATH="$WORKTREE_PATH"
    INTEGRATION_SOURCE="$WORKTREE_PATH/custom_components/ev_trip_planner"
    log_info "Using explicit worktree from ralph-loop: $INTEGRATION_SOURCE"
else
    # Try to find the last used worktree
    last_worktree_file="$PROJECT_DIR/.worktrees/last_worktree"
    if [[ -f "$last_worktree_file" ]]; then
        last_worktree=$(cat "$last_worktree_file" 2>/dev/null || echo "")
        if [[ -n "$last_worktree" && -d "$last_worktree" ]]; then
            WORKTREE_PATH="$last_worktree"
            INTEGRATION_SOURCE="$last_worktree/custom_components/ev_trip_planner"
            log_info "Using last worktree from $last_worktree_file: $INTEGRATION_SOURCE"
        fi
    fi
    
    # If no worktree found, use main repo with WARNING
    if [[ -z "$INTEGRATION_SOURCE" ]]; then
        INTEGRATION_SOURCE="$PROJECT_DIR/custom_components/ev_trip_planner"
        log_warn "NO WORKTREE DETECTED - using main repo (THIS MAY CAUSE ISSUES)"
        log_warn "You should run this script from within ralph-loop for proper worktree integration"
    fi
fi

# Save the current worktree for future use (if it's a worktree)
if [[ -n "$WORKTREE_PATH" && "$WORKTREE_PATH" != "$PROJECT_DIR" ]]; then
    echo "$WORKTREE_PATH" > "$last_worktree_file"
    log_info "Saved worktree to $last_worktree_file for future use"
fi

# ============================================================================
# UPDATE .env FILE WITH CORRECT INTEGRATION SOURCE
# This ensures the .env file always has the correct worktree path
# ============================================================================

update_env_file() {
    local env_file="$TEST_HA_DIR/.env"
    log_info "Updating $env_file with correct integration source..."
    
    # Create .env file with correct configuration
    cat > "$env_file" << 'ENVEOF'
# Environment variables for Home Assistant test container
# These are loaded by docker-compose automatically
#
# ⚠ GUARDRAIL: DO NOT EDIT THIS FILE MANUALLY
# This file is automatically updated by start_test_ha.sh
# If you need to change the integration source, use the WORKTREE_PATH environment variable

# Integration source - use worktree path when running from ralph-loop
INTEGRATION_SOURCE=<INTEGRATION_SOURCE_PLACEHOLDER>
# EMHASS config path - use environment variable with sensible default
EMHASS_CONFIG_PATH="${EMHASS_CONFIG_PATH:-/mnt/bunker_data/ha-ev-trip-planner/test-ha/config}"
ENVEOF

    # Replace placeholder with actual integration source
    sed -i "s|<INTEGRATION_SOURCE_PLACEHOLDER>|$INTEGRATION_SOURCE|g" "$env_file"
    
    log_ok "Updated $env_file with INTEGRATION_SOURCE=$INTEGRATION_SOURCE"
}

# ============================================================================
# CONTAINER STATUS CHECKS
# ============================================================================

is_running() {
    docker ps --format '{{.Names}}' | grep -q "^${HA_CONTAINER}$"
}

container_exists() {
    docker ps -a --format '{{.Names}}' | grep -q "^${HA_CONTAINER}$"
}

# ============================================================================
# WAIT FOR HA TO BE READY
# ============================================================================

wait_for_ha() {
    local max_retries=30
    local retry_interval=5

    log_info "Waiting for Home Assistant to be ready..."

    for i in $(seq 1 $max_retries); do
        # Check if container is running and healthy
        local container_status
        container_status=$(docker inspect --format='{{.State.Status}}' "$HA_CONTAINER" 2>/dev/null || echo "not_found")
        
        if [[ "$container_status" == "running" ]]; then
            # Container is running, give it a bit more time to fully initialize
            sleep 3
            log_ok "Home Assistant is ready! (container running)"
            return 0
        fi
        
        echo "Waiting for HA... ($i/$max_retries) status: $container_status"
        sleep $retry_interval
    done

    log_error "Home Assistant container is not running"
    return 1
}

# ============================================================================
# MAIN
# ============================================================================

main() {
    local wait_only=false

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --wait-only)
                wait_only=true
                shift ;;
            -h|--help)
                echo "Usage: $0 [--wait-only]"
                echo ""
                echo "Options:"
                echo "  --wait-only  Only wait if container is already running"
                exit 0
                ;;
            *)
                shift ;;
        esac
    done

    cd "$TEST_HA_DIR"

    # ALWAYS update .env file with correct integration source
    update_env_file

    log_info "Starting Home Assistant test container..."

    # CRITICAL: DO NOT RESTART container if already running
    # This prevents volume mismatches when agent runs docker-compose down/up
    if is_running; then
        log_ok "Container $HA_CONTAINER is already running - NOT restarting"
        log_info "This prevents volume configuration issues"
    elif container_exists; then
        log_info "Container exists but stopped, starting..."
        docker start "$HA_CONTAINER"
    else
        log_info "Creating and starting new container..."

        # Ensure config directory exists
        mkdir -p "$TEST_HA_DIR/config"

        # Note: EMHASS config is mounted via docker-compose volume, no copy needed

        # Pull latest image
        log_info "Pulling latest Home Assistant image..."
        docker-compose pull

        # Create and start container with environment variables
        INTEGRATION_SOURCE="$INTEGRATION_SOURCE" \
        EMHASS_CONFIG_PATH="${EMHASS_CONFIG_PATH:-/mnt/bunker_data/ha-ev-trip-planner/test-ha/config}" \
        docker-compose up -d
    fi

    # Wait for HA to respond (with polling instead of fixed sleep)
    log_info "Waiting for Home Assistant to be ready..."
    wait_for_ha

    log_ok "Home Assistant test container is ready at $HA_URL"
    log_info "Pre-configured state loaded from volume:"
    log_info "  - HACS: pre-installed"
    log_info "  - Mock sensors: ready"
    log_info "Use: HA_URL=$HA_URL npx playwright test"
}

main "$@"
