import { test, expect } from '@playwright/test';
import * as path from 'path';
import { ConfigFlowPage } from './pages/ConfigFlowPage';
import { EVTripPlannerPage } from './pages/EVTripPlannerPage';

const authFile = path.join(__dirname, '..', '..', 'playwright', '.auth', 'user.json');

test.describe('Trip Creation', () => {
  let configFlow: ConfigFlowPage;
  let panel: EVTripPlannerPage;
  let vehicleName: string;

  test.beforeEach(async ({ page }) => {
    await page.context().storageState({ path: authFile });

    configFlow = new ConfigFlowPage(page);
    panel = new EVTripPlannerPage(page);

    vehicleName = `TripTest${Date.now()}`;

    // Create vehicle via Config Flow (same flow as vehicle.spec.ts)
    await page.goto('/config/integrations');
    await configFlow.addIntegration('EV Trip Planner');
    await configFlow.fillVehicleName(vehicleName);
    await configFlow.submit();
    await configFlow.submit();
    await configFlow.submit();
    await configFlow.submit();
    await configFlow.submit();
    await configFlow.waitForPanelInSidebar();
  });

  test.afterEach(async ({ page }) => {
    // Delete all trips via UI
    const vehicleId = vehicleName.toLowerCase().replace(/\s+/g, '_');
    await page.goto(`/ev-trip-planner-${vehicleId}`).catch(() => {});
    await panel.addTripBtn.waitFor({ state: 'visible', timeout: 10000 }).catch(() => {});

    // Handle dialog once before any deletion
    let dialogHandled = false;
    const dialogHandler = () => { dialogHandled = true; };
    page.on('dialog', dialogHandler);

    // Delete any visible trip cards
    const deleteButtons = page.locator('ev-trip-planner-panel >> .delete-btn');
    const count = await deleteButtons.count();
    for (let i = 0; i < count; i++) {
      if (dialogHandled) break;
      try {
        await deleteButtons.first().click({ timeout: 2000 });
        await page.waitForTimeout(500);
      } catch {
        break;
      }
    }

    page.off('dialog', dialogHandler);

    // Remove integration
    await page.goto('/config/integrations');
    const integrationRow = page.locator('hass-integration-card', { hasText: vehicleName });
    if (await integrationRow.isVisible()) {
      await integrationRow.getByRole('button', { name: 'Delete' }).click();
      await page.getByRole('button', { name: 'Delete' }).click();
      await page.waitForTimeout(1000);
    }
  });

  test('US-3 + US-4: create recurring trip and verify it appears', async () => {
    // Open panel
    await panel.openFromSidebar();

    // Create trip
    await panel.openAddTripForm();
    await panel.createRecurringTrip({
      day: 1,       // Lunes
      time: '08:30',
      km: 25.5,
      kwh: 5.2,
      description: 'Commute to work',
    });

    // Verify trip card appears in list
    // The trip ID is generated by HA; we verify by waiting for any card to appear
    // and checking the form closes
    await expect(panel.tripFormOverlay).toBeHidden();
    const tripCards = page.locator('ev-trip-planner-panel >> .trip-card');
    await expect(tripCards.first()).toBeVisible({ timeout: 10000 });

    // Verify trip details via text content
    await expect(page.locator('ev-trip-planner-panel >> .trip-card')).toContainText('08:30');
    await expect(page.locator('ev-trip-planner-panel >> .trip-card')).toContainText('25.5');
  });

  test('US-3 + US-4: create punctual trip and verify it appears', async () => {
    await panel.openFromSidebar();
    await panel.openAddTripForm();

    // Select punctual type
    await panel.tripTypeSelect.selectOption('puntual');

    // Fill punctual-specific fields
    await page.locator('ev-trip-planner-panel >> #trip-datetime').fill('2026-04-15T09:00');
    await panel.tripKmInput.fill('100');
    await panel.tripKwhInput.fill('20');

    await panel.tripSubmitBtn.click();
    await expect(panel.tripFormOverlay).toBeHidden();

    const tripCards = page.locator('ev-trip-planner-panel >> .trip-card');
    await expect(tripCards.first()).toBeVisible({ timeout: 10000 });
    await expect(page.locator('ev-trip-planner-panel >> .trip-card')).toContainText('100');
  });
});
