data:
  last_update: '2026-03-25T01:36:18.578019'
  punctual_trips: {}
  recurring_trips:
    rec_0_e0y6py:
      activo: true
      descripcion: sdfgsdffg
      dia_semana: '0'
      hora: 01:31
      id: rec_0_e0y6py
      km: 34.0
      kwh: 34.0
      tipo: recurrente
    rec_0_iejc81:
      activo: true
      descripcion: asdfasd
      dia_semana: '0'
      hora: 01:20
      id: rec_0_iejc81
      km: 34.0
      kwh: 34.0
      tipo: recurrente
    rec_0_lvepsl:
      activo: true
      descripcion: asdf
      dia_semana: '0'
      hora: 01:36
      id: rec_0_lvepsl
      km: 234.0
      kwh: 234.0
      tipo: recurrente
  trips: {}
version: 1
